# Generated by Django 3.2.8 on 2022-09-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enviromentalIdicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCode', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
                ('blackCarbon', models.FloatField(default=0)),
                ('pm1', models.FloatField(default=0)),
                ('pm25', models.FloatField(default=0)),
                ('pm10', models.FloatField(default=0)),
            ],
        ),
    ]
