# Generated by Django 3.2.8 on 2022-09-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviromentalidicators',
            options={'verbose_name': 'enviromentalIdicator', 'verbose_name_plural': 'enviromentalIdicators'},
        ),
    ]
