# Generated by Django 3.2.8 on 2022-09-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_alter_enviromentalidicators_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviromentalidicators',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enviromentalidicators',
            name='idCode',
            field=models.IntegerField(default=0),
        ),
    ]
