# Generated by Django 3.2.8 on 2022-09-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_auto_20220902_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='enviromentalFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('remark', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'envirimentalFile',
                'verbose_name_plural': 'envirimentalFiles',
            },
        ),
    ]
